name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build

      #setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SHHKEYM }}" > "$HOME/.ssh/SHHKEYM"
      - run: chmod 600 "$HOME/.ssh/SHHKEYM"
      #deploy
      - run: cd build && rsync -e "ssh -i $HOME/.ssh/SHHKEYM -o StrictHostKeyChecking=no" -a --compress --delete . frontend@3.143.136.254:/var/www/help-algebra-finance/